Add CRUD Career
SimonLucasEsq/uex-app pull request #4
Opened 2023-03-07 19:56 UTC by magymonse

2023-03-08 02:01 UTC, SimonLucasEsq requested changes

2023-03-08 02:01 UTC, SimonLucasEsq commented on src/stores/career.js
> +    description: null,
No es necesario este atributo

2023-03-14 21:19 UTC, magymonse commented on src/pages/careers/index.vue
> +#career-list {
Cambiar a que nombre?

2023-03-23 22:54 UTC, SimonLucasEsq approved these changes

2023-03-23 23:00 UTC, merged